version: '3.9'

services:
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todo123
      POSTGRES_DB: todo_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"