spring:
  application:
    name: todo-app
  datasource:
    url: jdbc:postgresql://192.168.1.190:5434/todo_db?currentSchema=todo_schema
    username: todouser
    password: todo123
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 2
#    jpa:
#      properties:
#        hibernate:
#          show_sql: true
#          format_sql: true
